title: Typehackery
description: a collection of stuff that isn't supposed to be written in the type system but is.
theme: just-the-docs

url: https://mchccn.github.io/typehackery

aux_links:
    Repository: https://github.com/mchccn/typehackery
