title: typehackery
description: a collection of stuff that isn't supposed to be written in the type system but is.
theme: just-the-docs
color_scheme: typehackery

url: https://mchccn.github.io/typehackery

aux_links:
    Repository: https://github.com/mchccn/typehackery

search_enabled: true

mermaid:
    version: "10.9.1"
